name: Build MTG Cards JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # tous les dimanches à minuit UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run script to build MTGCards.json
        run: node processCards.js

      - name: Upload MTGCards.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: MTGCards
          path: MTGCards.json
